### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by isorensen** [linkapi/getokr-api#1]
Dear all,
I'm trying to install getokr-api (and after that, getokr-web). However, it gives me an error.
I'm running node and npm version as recommended in README file. Below is the error. I appreciate any help.
```
ubuntu@ip-172-31-0-142:~/getokr/getokr-api$ node -v
v8.11.1
ubuntu@ip-172-31-0-142:~/getokr/getokr-api$ npm -v
3.10.10
ubuntu@ip-172-31-0-142:~/getokr/getokr-api$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN getokr-api@1.0.0 No repository field.
ubuntu@ip-172-31-0-142:~/getokr/getokr-api$ npm run seed

> getokr-api@1.0.0 seed /home/ubuntu/getokr/getokr-api
> node ./database/run.js


/home/ubuntu/getokr/getokr-api/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

npm ERR! Linux 4.15.0-1051-aws
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v8.11.1/bin/node" "/home/ubuntu/.nvm/versions/node/v8.11.1/bin/npm" "run" "seed"
npm ERR! node v8.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! getokr-api@1.0.0 seed: `node ./database/run.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getokr-api@1.0.0 seed script 'node ./database/run.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the getokr-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./database/run.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs getokr-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls getokr-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/getokr/getokr-api/npm-debug.log
```

**Comment by isorensen** [comment]
Mongodb não estava rodando. Após instalação manual do Mongodb, funcionou. Valeu
